const MainPageActionTypes = {
  FETCH_SEARCH_RESULTS_START: "FETCH_SEARCH_RESULTS_START",
  FETCH_SEARCH_RESULTS_SUCCESS: "FETCH_SEARCH_RESULTS_SUCCESS",
  FETCH_MOVIE: "FETCH_MOVIE",
  FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
  HANDLE_IS_FAVORITE_MOVIE: "HANDLE_IS_FAVORITE_MOVIE",
  TOGGLE_FAVORITE_MOVIE: "TOGGLE_FAVORITE_MOVIE",
};

export default MainPageActionTypes;
