const MainPageActionTypes = {
  FETCH_SEARCH_RESULTS_START: "FETCH_SEARCH_RESULTS_START",
  FETCH_SEARCH_RESULTS_SUCCESS: "FETCH_SEARCH_RESULTS_SUCCESS",
  FETCH_SEARCH_RESULTS_FAILED: "FETCH_SEARCH_RESULTS_FAILED",
  RESET_SEARCH_RESULTS: "RESET_SEARCH_RESULTS",
  FETCH_MOVIE: "FETCH_MOVIE",
  FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
  FETCH_MOVIE_FAILED: "FETCH_MOVIE_FAILED",
  RESET_MODAL_MOVIE: "RESET_MODAL_MOVIE",
  HANDLE_IS_FAVORITE_MOVIE: "HANDLE_IS_FAVORITE_MOVIE",
  SET_IS_FAVORITE_TRUE: "SET_IS_FAVORITE_TRUE",
  SET_IS_FAVORITE_FALSE: "SET_IS_FAVORITE_FALSE",
  TOGGLE_FAVORITE_MOVIE: "TOGGLE_FAVORITE_MOVIE",
  SHOW_MODAL: "SHOW_MODAL",
};

export default MainPageActionTypes;
